-- Desktop decisions for this machine.
--
-- Generated by bin/ms from canonical/desktop/hypr/. Do not edit by hand:
-- edits are reported by `ms diff` and overwritten by `ms project`.
--
-- This module is loaded LAST by hyprland.lua, so what it sets overrides the
-- CachyOS template. The template files under config/ are left pristine, which
-- keeps "what CachyOS ships" and "what we decided" separable.

hl.config({
    input = {
        kb_layout = "gb",
    },
})

hl.monitor({
    output   = MONITOR1,
    mode     = "3840x2400@120",
    position = "auto",
    scale    = "auto",
})
